# Generated by Django 6.0.4 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='last_action',
            field=models.CharField(default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='mode',
            field=models.CharField(default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='override_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
