# Generated by Django 6.0.4 on 2026-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_devicestate_last_action_devicestate_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='relay',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
