# Generated by Django 6.0.4 on 2026-04-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sensordata_relay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicestate',
            old_name='override_until',
            new_name='manual_started_at',
        ),
    ]
