# Generated by Django 6.0.4 on 2026-04-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_override_until_devicestate_manual_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='farm_active',
            field=models.BooleanField(default=False),
        ),
    ]
