# Generated by Django 6.0.4 on 2026-04-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_devicestate_farm_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='manual_button',
            new_name='ammonia_high',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='relay',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='any_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='humidity_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='light_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='sensor_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temp_high',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='temp_low',
            field=models.BooleanField(default=False),
        ),
    ]
