# Generated by Django 6.0.4 on 2026-04-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_manual_button_sensordata_ammonia_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shed_type', models.CharField(choices=[('meat', 'Meat'), ('eggs', 'Eggs')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceState',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='ammonia_high',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='any_alert',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity_high',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='humidity_low',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='light_low',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temp_high',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='temp_low',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shed'),
        ),
        migrations.AddField(
            model_name='batch',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shed'),
        ),
    ]
