# Generated by Django 6.0.4 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_batch_device_shed_delete_devicestate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_type', models.CharField(choices=[('meat', 'Meat'), ('eggs', 'Eggs')], max_length=20)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('day_number', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
