# Generated by Django 6.0.4 on 2026-04-18 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_vaccineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='bird_count_initial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('scheduled_day', models.IntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('due', 'Due'), ('done', 'Done'), ('overdue', 'Overdue')], default='due', max_length=20)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
        ),
    ]
