# Generated by Django 6.0.4 on 2026-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_batch_batch_number_batch_bird_count_initial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccinerecord',
            options={'ordering': ['due_date', 'scheduled_day', 'vaccine_name']},
        ),
        migrations.AlterModelOptions(
            name='vaccineschedule',
            options={'ordering': ['day_number', 'vaccine_name']},
        ),
        migrations.AddField(
            model_name='batch',
            name='starting_age_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vaccinerecord',
            name='scheduled_day',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='day_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinerecord',
            unique_together={('batch', 'vaccine_name', 'scheduled_day')},
        ),
    ]
