# Generated by Django 6.0.4 on 2026-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_vaccinerecord_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_type', models.CharField(choices=[('meat', 'Meat'), ('layer', 'Layer')], max_length=20)),
                ('min_age_days', models.IntegerField()),
                ('max_age_days', models.IntegerField()),
                ('low_temp', models.FloatField()),
                ('high_temp', models.FloatField()),
            ],
        ),
    ]
