# Generated by Django 6.0.4 on 2026-04-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_temperaturerule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shed',
            name='shed_type',
            field=models.CharField(choices=[('meat', 'Meat'), ('layer', 'Layer')], max_length=20),
        ),
    ]
