# Generated by Django 6.0.4 on 2026-04-28 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_batch_end_date_batch_status_salerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='average_weight',
        ),
        migrations.RemoveField(
            model_name='salerecord',
            name='rate_per_kg',
        ),
        migrations.RemoveField(
            model_name='salerecord',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='sale_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
