# Generated by Django 6.0.4 on 2026-04-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_salerecord_average_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='average_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='rate_per_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
