# Generated by Django 6.0.4 on 2026-04-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_salerecord_average_weight_kg_salerecord_rate_per_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='total_amount',
        ),
    ]
