# Generated by Django 6.0.4 on 2026-05-31 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userfeedstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortalityrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
