# Generated by Django 6.0.4 on 2026-06-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_mortalityrecord_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chick_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('carriage_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
            ],
        ),
    ]
