# Generated by Django 6.0.4 on 2026-06-03 21:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_batchcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='average_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='birds_sold',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='rate_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
