# Generated by Django 6.0.4 on 2026-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_salerecord_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerecord',
            name='average_weight_kg',
        ),
        migrations.AddField(
            model_name='salerecord',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
