# Generated by Django 6.0.4 on 2026-06-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_salerecord_average_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
