# Generated by Django 6.0.4 on 2026-06-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_salerecord_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salerecord',
            name='cogs_allocated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='cogs_per_bird_at_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salerecord',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
