# Generated by Django 6.0.4 on 2026-06-07 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_salerecord_cogs_allocated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('diesel', 'Diesel'), ('labor', 'Labor'), ('electricity', 'Electricity'), ('maintenance', 'Maintenance'), ('transport', 'Transport'), ('misc', 'Misc')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.batch')),
            ],
        ),
    ]
