# Generated by Django 6.0.4 on 2026-06-07 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('labor', 'Labor'), ('electricity', 'Electricity'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('misc', 'Misc')], max_length=50),
        ),
    ]
