# Generated by Django 6.0.4 on 2026-06-07 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_expense_batch_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('labor', 'Labor'), ('electricity', 'Electricity'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('rent', 'Farm Rent'), ('internet', 'Internet'), ('service', 'Service Charges'), ('misc', 'Misc')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
