# Generated by Django 6.0.4 on 2026-06-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_chickcostentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chickcostentry',
            name='amount',
        ),
        migrations.AddField(
            model_name='chickcostentry',
            name='carriage_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chickcostentry',
            name='chick_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
