# Generated by Django 6.0.4 on 2026-07-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_chickcostentry_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineentry',
            name='medicine_name',
            field=models.CharField(default='Not specified', max_length=120),
        ),
        migrations.AddField(
            model_name='medicineentry',
            name='medicine_type',
            field=models.CharField(choices=[('vaccine', 'Vaccine'), ('medicine', 'Medicine'), ('multivitamin', 'Multivitamin')], default='medicine', max_length=20),
        ),
    ]
