# Generated by Django 6.0.4 on 2026-07-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('labor', 'Labor'), ('electricity', 'Electricity'), ('transport', 'Transport'), ('maintenance', 'Maintenance'), ('rent', 'Farm Rent'), ('internet', 'Internet'), ('service', 'Service Charges'), ('misc', 'Misc')], max_length=50),
        ),
    ]
