# Generated by Django 6.0.4 on 2026-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_type',
            field=models.CharField(choices=[('meat', 'Meat'), ('layer', 'Layer')], default='meat', max_length=20),
        ),
    ]
