# Generated by Django 6.0.4 on 2026-08-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_useractivitylog_useractivitystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disabled devices will be ignored by the dashboard.'),
        ),
    ]
