# Generated by Django 6.0.4 on 2026-08-01 22:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_device_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_number', models.PositiveSmallIntegerField(help_text='Physical relay-board channel from 1 to 16.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('gpio_pin', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(39)])),
                ('name', models.CharField(help_text='Example: Shed Light 1, Exhaust Fan, Water Motor.', max_length=100)),
                ('load_type', models.CharField(choices=[('normal', 'Normal Output'), ('motor', 'Motor / Fan Output')], default='normal', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled channels cannot be operated from the dashboard.')),
                ('desired_state', models.BooleanField(default=False)),
                ('actual_state', models.BooleanField(default=False)),
                ('commanded_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_commands', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relay_channels', to='api.device')),
            ],
            options={
                'ordering': ['device_id', 'channel_number'],
                'constraints': [models.UniqueConstraint(fields=('device', 'channel_number'), name='unique_relay_channel_per_device'), models.UniqueConstraint(fields=('device', 'gpio_pin'), name='unique_relay_gpio_per_device')],
            },
        ),
    ]
