# Generated by Django 6.0.4 on 2026-09-29 21:31

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_goat_sale_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EggPOSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('default_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('low_stock_eggs', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg POS Product',
                'verbose_name_plural': 'Egg POS Products',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EggPOSSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg POS Supplier',
                'verbose_name_plural': 'Egg POS Suppliers',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EggPOSFarmTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_pos_transfers', to='api.batch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_pos_farm_transfers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggPOSInventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('purchase', 'Purchased Eggs'), ('farm', 'RayNoor Farm Eggs')], max_length=20)),
                ('lot_code', models.CharField(max_length=60, unique=True)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_pos_inventory_lots', to='api.batch')),
                ('farm_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='api.eggposfarmtransfer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='api.eggposproduct')),
            ],
            options={
                'ordering': ['received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EggPOSFarmTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='POS inventory cost per egg for this farm transfer.', max_digits=10)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.eggposfarmtransfer')),
                ('lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_transfer_item', to='api.eggposinventorylot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.eggposproduct')),
            ],
        ),
        migrations.CreateModel(
            name='EggPOSPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_pos_purchases_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_pos_purchases', to='api.eggpossupplier')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='eggposinventorylot',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lots', to='api.eggpospurchase'),
        ),
        migrations.CreateModel(
            name='EggPOSPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item', to='api.eggposinventorylot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.eggposproduct')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.eggpospurchase')),
            ],
        ),
        migrations.CreateModel(
            name='EggPOSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('net_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cogs_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('profit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egg_pos_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EggPOSSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cogs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.eggposproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.eggpossale')),
            ],
        ),
        migrations.CreateModel(
            name='EggPOSSaleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cogs_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='api.eggposinventorylot')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_allocations', to='api.eggpossaleitem')),
            ],
            options={
                'ordering': ['lot__received_date', 'lot_id'],
            },
        ),
        migrations.AddField(
            model_name='eggposinventorylot',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_pos_inventory_lots', to='api.eggpossupplier'),
        ),
        migrations.CreateModel(
            name='EggPOSUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_sell', models.BooleanField(default=True)),
                ('can_manage', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_pos_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egg POS User Access',
                'verbose_name_plural': 'Egg POS User Access',
            },
        ),
    ]
