# Generated by Django 6.0.4 on 2026-10-01 20:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_mark_fan_relays_as_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goatsalepayout',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
