from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0059_alter_goatsalepayout_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChartOfAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("account_type", models.CharField(choices=[("asset", "Asset"), ("liability", "Liability"), ("equity", "Equity"), ("revenue", "Revenue"), ("cogs", "Cost of Goods Sold"), ("expense", "Expense")], max_length=20)),
                ("normal_balance", models.CharField(choices=[("debit", "Debit"), ("credit", "Credit")], max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Chart of Account", "verbose_name_plural": "Chart of Accounts", "ordering": ["code", "id"]},
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField(default=django.utils.timezone.localdate)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("module", models.CharField(choices=[("egg_pos", "Egg POS"), ("poultry", "Poultry"), ("goat", "Goat"), ("general", "General")], default="general", max_length=20)),
                ("source_type", models.CharField(blank=True, max_length=60)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("source_key", models.CharField(max_length=160, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="journal_entries_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["entry_date", "id"]},
        ),
        migrations.CreateModel(
            name="JournalLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("debit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("credit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("party_type", models.CharField(blank=True, choices=[("", "None"), ("supplier", "Supplier"), ("customer", "Customer"), ("user", "Staff / Salesperson"), ("farm", "Farm / Internal Unit")], default="", max_length=20)),
                ("party_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("party_name", models.CharField(blank=True, max_length=180)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="journal_lines", to="api.chartofaccount")),
                ("entry", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="api.journalentry")),
            ],
            options={"ordering": ["entry__entry_date", "entry_id", "id"]},
        ),
        migrations.AddIndex(model_name="journalentry", index=models.Index(fields=["module", "entry_date"], name="api_je_module_date_idx")),
        migrations.AddIndex(model_name="journalentry", index=models.Index(fields=["source_type", "source_id"], name="api_je_source_idx")),
        migrations.AddIndex(model_name="journalline", index=models.Index(fields=["account", "party_type", "party_id"], name="api_jl_acct_party_idx")),
        migrations.AddIndex(model_name="journalline", index=models.Index(fields=["party_type", "party_id"], name="api_jl_party_idx")),
        migrations.AddField(
            model_name="eggposuseraccess",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), help_text="Percentage of commissionable profit earned by this salesperson.", max_digits=5),
        ),
        migrations.AddField(
            model_name="eggpospurchase",
            name="transport_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="eggpospurchase",
            name="transport_payment_method",
            field=models.CharField(choices=[("cash", "Company Cash"), ("bank_transfer", "Bank Transfer"), ("supplier_payable", "Add to Supplier Payable"), ("other", "Other Company Payment")], default="cash", max_length=30),
        ),
        migrations.AddField(
            model_name="eggposfarmtransfer",
            name="transport_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=14),
        ),
        migrations.AddField(
            model_name="eggposfarmtransfer",
            name="transport_payment_method",
            field=models.CharField(choices=[("cash", "Company Cash"), ("bank_transfer", "Bank Transfer"), ("other", "Other Company Payment")], default="cash", max_length=30),
        ),
        migrations.AlterField(model_name="eggposinventorylot", name="unit_cost", field=models.DecimalField(decimal_places=6, max_digits=14)),
        migrations.AlterField(model_name="eggpospurchaseitem", name="unit_cost", field=models.DecimalField(decimal_places=6, max_digits=14)),
        migrations.AlterField(model_name="eggposfarmtransferitem", name="unit_cost", field=models.DecimalField(decimal_places=6, help_text="Base transfer cost per egg before inbound transport allocation.", max_digits=14)),
        migrations.AlterField(model_name="eggpossaleallocation", name="unit_cost", field=models.DecimalField(decimal_places=6, max_digits=14)),
        migrations.CreateModel(
            name="EggPOSSupplierPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer"), ("easypaisa", "Easypaisa"), ("jazzcash", "JazzCash"), ("other", "Other")], default="cash", max_length=30)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purchase", models.ForeignKey(blank=True, help_text="Optional purchase invoice this payment relates to.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="api.eggpospurchase")),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_supplier_payments_recorded", to=settings.AUTH_USER_MODEL)),
                ("supplier", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="api.eggpossupplier")),
            ],
            options={"ordering": ["payment_date", "id"]},
        ),
        migrations.CreateModel(
            name="EggPOSExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("expense_date", models.DateField(default=django.utils.timezone.localdate)),
                ("expense_type", models.CharField(choices=[("fuel", "Fuel"), ("delivery", "Delivery / Rider"), ("toll_parking", "Toll / Parking"), ("packaging", "Packaging"), ("other", "Other Selling Expense")], default="fuel", max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_source", models.CharField(choices=[("sales_collection", "Deduct from Sales Collection"), ("personal", "Paid Personally - Reimburse Staff"), ("company_cash", "Paid by Company Cash"), ("company_bank", "Paid by Company Bank")], default="sales_collection", max_length=30)),
                ("affects_commission", models.BooleanField(default=True)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending Approval"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_expenses_approved", to=settings.AUTH_USER_MODEL)),
                ("entered_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_expenses_entered", to=settings.AUTH_USER_MODEL)),
                ("used_by", models.ForeignKey(help_text="Salesperson/staff member whose selling activity used this expense.", on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_expenses_used", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-expense_date", "-id"]},
        ),
        migrations.AddIndex(model_name="eggposexpense", index=models.Index(fields=["used_by", "expense_date", "status"], name="api_exp_user_date_idx")),
        migrations.CreateModel(
            name="EggPOSCashSettlement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("settlement_date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("destination", models.CharField(choices=[("cash", "Main Cash"), ("bank_transfer", "Bank")], default="cash", max_length=30)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_cash_settlements_recorded", to=settings.AUTH_USER_MODEL)),
                ("salesperson", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_cash_settlements", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-settlement_date", "-id"]},
        ),
        migrations.CreateModel(
            name="EggPOSCommissionPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("sales_revenue", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("cogs", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("selling_expenses", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("commissionable_profit", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("commission_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("commission_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=16)),
                ("notes", models.TextField(blank=True)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("posted_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_commissions_posted", to=settings.AUTH_USER_MODEL)),
                ("salesperson", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_commission_periods", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-period_end", "-id"]},
        ),
        migrations.AddConstraint(model_name="eggposcommissionperiod", constraint=models.UniqueConstraint(fields=("salesperson", "period_start", "period_end"), name="uniq_egg_pos_commission_period")),
        migrations.CreateModel(
            name="EggPOSCommissionPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_date", models.DateField(default=django.utils.timezone.localdate)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_method", models.CharField(choices=[("cash", "Cash"), ("bank_transfer", "Bank Transfer"), ("easypaisa", "Easypaisa"), ("jazzcash", "JazzCash"), ("other", "Other")], default="bank_transfer", max_length=30)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("commission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="api.eggposcommissionperiod")),
                ("recorded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="egg_pos_commission_payments_recorded", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["payment_date", "id"]},
        ),
    ]
