# Generated by Django 6.0.4 on 2026-10-08 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_direct_egg_sale_corrections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmEggCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance (not previously recorded)'), ('capital_in', 'Capital introduced'), ('other_in', 'Other cash received'), ('expense', 'Payment for an already recorded farm expense'), ('withdrawal', 'Owner/investor withdrawal'), ('other_out', 'Other payment out'), ('cash_to_bank', 'Transfer physical cash to bank'), ('bank_to_cash', 'Withdraw bank funds into physical cash')], max_length=22)),
                ('account', models.CharField(choices=[('cash', 'Physical cash'), ('bank', 'Bank / wallet')], default='cash', max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_voided', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='egg_cash_movements', to='api.batch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_egg_cash_movements_created', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_egg_cash_movements_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
    ]
