# Generated by Django 6.0.4 on 2026-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_farmeggcashmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('outside', 'Paid externally / staff or investor funds (not farm cashbook)'), ('farm_cash', 'Paid from Farm Management Cash in Hand'), ('farm_bank', 'Paid from Farm Management Bank / Wallet'), ('unpaid', 'Unpaid / Supplier credit')], default='outside', help_text='How this expense was paid; farm cash/bank entries flow into the Egg Farm Cashbook automatically.', max_length=12),
        ),
        migrations.AddField(
            model_name='feedentry',
            name='payment_source',
            field=models.CharField(choices=[('outside', 'Paid externally / staff or investor funds (not farm cashbook)'), ('farm_cash', 'Paid from Farm Management Cash in Hand'), ('farm_bank', 'Paid from Farm Management Bank / Wallet'), ('unpaid', 'Unpaid / Supplier credit')], default='outside', max_length=12),
        ),
        migrations.AddField(
            model_name='medicineentry',
            name='payment_source',
            field=models.CharField(choices=[('outside', 'Paid externally / staff or investor funds (not farm cashbook)'), ('farm_cash', 'Paid from Farm Management Cash in Hand'), ('farm_bank', 'Paid from Farm Management Bank / Wallet'), ('unpaid', 'Unpaid / Supplier credit')], default='outside', max_length=12),
        ),
    ]
