from django.urls import path
from api.views import sensor, camera, sales, logs, finance_tracker, investor_accounts, eggs, goats, goat_age, egg_pos


urlpatterns = [
    path("sensor-data/", sensor.receive_sensor_data),
path(
    "relay-commands/",
    sensor.get_relay_commands,
    name="get_relay_commands",
),
path(
    "relay-status/",
    sensor.report_relay_states,
    name="report_relay_states",
),

path(
    "relay-control/",
    sensor.relay_control,
    name="relay_control",
),

path(
    "relay-control/<int:relay_id>/set/",
    sensor.set_relay_state,
    name="set_relay_state",
),

path(
    "relay-control/status/",
    sensor.relay_status_snapshot,
    name="relay_status_snapshot",
),

path(
    "relay-control/<int:relay_id>/automation/",
    sensor.relay_automation,
    name="relay_automation",
),
path(
    "relay-control/<int:relay_id>/resume-auto/",
    sensor.resume_relay_auto,
    name="resume_relay_auto",
),
path(
    "relay-control/<int:relay_id>/",
    sensor.relay_detail,
    name="relay_detail",
),
    path("dashboard/", sensor.dashboard, name="dashboard"),
    path("vaccines/<int:batch_id>/", sensor.vaccine_records, name="vaccine_records"),
    path("ownership-shares/", sensor.ownership_shares, name="ownership_shares"),
    path("vaccines/done/<int:record_id>/", sensor.mark_vaccine_done, name="mark_vaccine_done"),
    path("active-batches/", sensor.active_batches, name="active_batches"),
    path("active-batches/close/<int:batch_id>/", sensor.close_batch, name="close_batch"),
    path("profile/", sensor.user_profile, name="user_profile"),
    path("batch/<int:batch_id>/close/", sales.close_batch, name="close_batch"),
    path("batch/<int:batch_id>/sales/", sales.sale_records, name="sale_records"),
    path("meat-sales/", sales.meat_sales_summary, name="meat_sales_summary"),
    path("meat-sales/<int:batch_id>/", sales.meat_sale_detail, name="meat_sale_detail"),
    path("daily-log/", logs.daily_log, name="daily_log"),
    path("eggs/", eggs.egg_dashboard, name="egg_dashboard"),
    path("eggs/production/add/", eggs.add_egg_production, name="add_egg_production"),
    path("eggs/active-hens/", eggs.active_hens_history, name="active_hens_history"),
    path("eggs/sales/add/", eggs.add_egg_sale, name="add_egg_sale"),
    path("eggs/sales/<int:sale_id>/manage/", eggs.manage_egg_sale, name="manage_egg_sale"),
    path("eggs/damage/add/", eggs.add_egg_damage, name="add_egg_damage"),
    path("egg-pos/", egg_pos.dashboard, name="egg_pos_dashboard"),
    path("egg-pos/inventory/", egg_pos.inventory, name="egg_pos_inventory"),
    path("egg-pos/products/", egg_pos.products, name="egg_pos_products"),
    path("egg-pos/suppliers/", egg_pos.suppliers, name="egg_pos_suppliers"),
    path("egg-pos/suppliers/<int:supplier_id>/", egg_pos.supplier_detail, name="egg_pos_supplier_detail"),
    path("egg-pos/purchases/", egg_pos.purchase_list, name="egg_pos_purchase_list"),
    path("egg-pos/purchases/add/", egg_pos.add_purchase, name="egg_pos_add_purchase"),
    path("egg-pos/purchases/<int:purchase_id>/edit/", egg_pos.edit_purchase, name="egg_pos_edit_purchase"),
    path("egg-pos/farm-transfer/", egg_pos.farm_transfer, name="egg_pos_farm_transfer"),
    path("egg-pos/farm-transfer/<int:transfer_id>/", egg_pos.farm_transfer_detail, name="egg_pos_farm_transfer_detail"),
    path("egg-pos/farm-transfer/<int:transfer_id>/edit/", egg_pos.edit_farm_transfer, name="egg_pos_edit_farm_transfer"),
    path("egg-pos/farm-transfer/<int:transfer_id>/void/", egg_pos.void_farm_transfer, name="egg_pos_void_farm_transfer"),
    path("egg-pos/farm-transfer/<int:transfer_id>/payment/", egg_pos.record_farm_transfer_payment, name="egg_pos_record_farm_transfer_payment"),
    path("egg-pos/sales/", egg_pos.sales, name="egg_pos_sales"),
    path("egg-pos/customers/", egg_pos.customers, name="egg_pos_customers"),
    path("egg-pos/customers/add/", egg_pos.add_customer, name="egg_pos_add_customer"),
    path("egg-pos/customers/<int:customer_id>/", egg_pos.customer_detail, name="egg_pos_customer_detail"),
    path("egg-pos/sales/new/", egg_pos.new_sale, name="egg_pos_new_sale"),
    path("egg-pos/sales/<int:sale_id>/", egg_pos.sale_detail, name="egg_pos_sale_detail"),
    path("egg-pos/sales/<int:sale_id>/invoice/", egg_pos.sale_invoice, name="egg_pos_sale_invoice"),
    path("egg-pos/sales/<int:sale_id>/payment/", egg_pos.record_sale_payment, name="egg_pos_record_sale_payment"),
    path("egg-pos/sales/<int:sale_id>/reverse/", egg_pos.reverse_pos_sale, name="egg_pos_reverse_sale"),
    path("egg-pos/sales/<int:sale_id>/edit/", egg_pos.edit_pos_sale, name="egg_pos_edit_sale"),
    path("egg-pos/sales/<int:sale_id>/restore/", egg_pos.undo_pos_sale_reversal, name="egg_pos_restore_sale"),
    path("egg-pos/staff-access/", egg_pos.staff_access, name="egg_pos_staff_access"),
    path("egg-pos/expenses/", egg_pos.expenses, name="egg_pos_expenses"),
    path("egg-pos/expenses/<int:expense_id>/approve/", egg_pos.approve_expense, name="egg_pos_approve_expense"),
    path("egg-pos/cash-settlements/", egg_pos.cash_settlements, name="egg_pos_cash_settlements"),
    path("egg-pos/commissions/", egg_pos.commissions, name="egg_pos_commissions"),
    path("egg-pos/accounts/", egg_pos.accounting_overview, name="egg_pos_accounting"),
    path("egg-pos/accounts/owner-capital/", egg_pos.owner_capital, name="egg_pos_owner_capital"),
    path("egg-pos/accounts/general-ledger/", egg_pos.general_ledger, name="egg_pos_general_ledger"),
    path("egg-pos/accounts/cashbook/", egg_pos.cashbook, name="egg_pos_cashbook"),
    path("egg-pos/accounts/trial-balance/", egg_pos.trial_balance, name="egg_pos_trial_balance"),
    path("egg-pos/accounts/income-statement/", egg_pos.income_statement, name="egg_pos_income_statement"),
    path("egg-pos/accounts/ledger/<str:party_type>/<int:party_id>/", egg_pos.party_ledger, name="egg_pos_party_ledger"),
    path("goats/", goats.goat_dashboard, name="goat_dashboard"),
    path("goats/add/", goats.add_goat, name="add_goat"),
    path("goats/<int:goat_id>/", goats.goat_detail, name="goat_detail"),
    path("goats/<int:goat_id>/weight/add/", goats.add_goat_weight, name="add_goat_weight"),
    path("goats/<int:goat_id>/pedigree/", goats.edit_goat_pedigree, name="edit_goat_pedigree"),
    path("goats/<int:goat_id>/dates/", goat_age.edit_goat_dates, name="edit_goat_dates"),
    path("goats/breeding/", goats.goat_breeding, name="goat_breeding"),
    path("goats/breeding/compatibility/", goats.goat_breeding_compatibility, name="goat_breeding_compatibility"),
    path("goats/breeding/<int:breeding_id>/status/", goats.update_goat_breeding_status, name="update_goat_breeding_status"),
    path("goats/breeding/<int:breeding_id>/kidding/", goats.record_goat_kidding, name="record_goat_kidding"),
    path("goats/costs/", goats.goat_costs, name="goat_costs"),
    path("goats/costs/add/<str:category>/", goats.add_goat_cost, name="add_goat_cost"),
    path("goats/finance/", goats.goat_finance, name="goat_finance"),
    path("goats/<int:goat_id>/sale/", goats.add_goat_sale, name="add_goat_sale"),
    path("goat-accounts/", goats.goat_accounts, name="goat_accounts"),
    path("goat-accounts/<int:owner_id>/", goats.goat_account_detail, name="goat_account_detail"),
    path("goat-accounts/<int:owner_id>/payment/", goats.record_goat_account_payment, name="record_goat_account_payment"),
    path("finance-tracker/", finance_tracker.finance_tracker, name="finance_tracker"),
    path("investor-accounts/", investor_accounts.investor_accounts, name="investor_accounts"),
    path("investor-accounts/<int:allocation_id>/", investor_accounts.investor_account_detail, name="investor_account_detail"),
    path("investor-accounts/<int:allocation_id>/payment/", investor_accounts.record_investor_account_payment, name="record_investor_account_payment"),
    path("investor-accounts/<int:allocation_id>/sale-payout/", investor_accounts.record_investor_sale_payout, name="record_investor_sale_payout"),
    path("investor-accounts/farm/<int:batch_id>/", investor_accounts.farm_account_detail, name="farm_account_detail"),
    path("investor-accounts/farm/<int:batch_id>/contribution/", investor_accounts.record_farm_account_payment, name="record_farm_account_payment"),
    path("investor-accounts/farm/<int:batch_id>/sale-withdrawal/", investor_accounts.record_farm_sale_withdrawal, name="record_farm_sale_withdrawal"),
    path("add-sale/", finance_tracker.add_sale_record, name="add_sale_record"),
    path("finance-tracker/batch/<int:batch_id>/all-birds-sold/", finance_tracker.mark_all_birds_sold, name="mark_all_birds_sold"),
    path("finance-tracker/batch/<int:batch_id>/undo-all-birds-sold/", finance_tracker.undo_all_birds_sold, name="undo_all_birds_sold"),
    path("feed-list/", finance_tracker.feed_list, name="feed_list"),
    path("add-feed/", finance_tracker.add_feed_entry, name="add_feed_entry"),
    path("medicine-list/", finance_tracker.medicine_list, name="medicine_list"),
    path("add-medicine/",finance_tracker.add_medicine_entry, name="add_medicine_entry"),
    path("expenses/", sales.expense_list, name="expense_list"),
    path("add-expense/",sales.add_expense,name="add_expense"),
    path("add-chick-cost/", finance_tracker.add_chick_cost, name="add_chick_cost"),
    path("batch-report/pdf/<int:batch_id>/investor/<int:allocation_id>/", finance_tracker.batch_report_pdf_investor,name="batch_report_pdf_investor"),
    path("batch-report/", finance_tracker.batch_report, name="batch_report"),
    path("dashboard-v2/", sensor.dashboard_v2, name="dashboard_v2"),
    path("logout/", sensor.logout_user, name="logout"),
    path("user-activity/", sensor.user_activity, name="user_activity"),



]